// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: server_client.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_UNKNOWN_CODE         Code = 0
	Code_BATCH                Code = 1
	Code_ON_PLAYER_CONNECT    Code = 10
	Code_ON_PLAYER_DISCONNECT Code = 11
	Code_PLAYER_LIST          Code = 12
	Code_CLIENT_INFO          Code = 20
	Code_QUIT                 Code = 21
	Code_SPAWN_PLAYER         Code = 50
	Code_SET_PLAYER_CLASS     Code = 51
	Code_SET_PLAYER_HP        Code = 52
	Code_SET_PLAYER_RADIUS    Code = 53
	Code_SET_PLAYER_SPEED     Code = 54
	Code_SET_PLAYER_POSITION  Code = 55
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "UNKNOWN_CODE",
		1:  "BATCH",
		10: "ON_PLAYER_CONNECT",
		11: "ON_PLAYER_DISCONNECT",
		12: "PLAYER_LIST",
		20: "CLIENT_INFO",
		21: "QUIT",
		50: "SPAWN_PLAYER",
		51: "SET_PLAYER_CLASS",
		52: "SET_PLAYER_HP",
		53: "SET_PLAYER_RADIUS",
		54: "SET_PLAYER_SPEED",
		55: "SET_PLAYER_POSITION",
	}
	Code_value = map[string]int32{
		"UNKNOWN_CODE":         0,
		"BATCH":                1,
		"ON_PLAYER_CONNECT":    10,
		"ON_PLAYER_DISCONNECT": 11,
		"PLAYER_LIST":          12,
		"CLIENT_INFO":          20,
		"QUIT":                 21,
		"SPAWN_PLAYER":         50,
		"SET_PLAYER_CLASS":     51,
		"SET_PLAYER_HP":        52,
		"SET_PLAYER_RADIUS":    53,
		"SET_PLAYER_SPEED":     54,
		"SET_PLAYER_POSITION":  55,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_server_client_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_server_client_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	Class_UNKNOWN_CLASS Class = 0
	Class_WARRIOR       Class = 1
	Class_MAGE          Class = 2
	Class_RANGER        Class = 3
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "UNKNOWN_CLASS",
		1: "WARRIOR",
		2: "MAGE",
		3: "RANGER",
	}
	Class_value = map[string]int32{
		"UNKNOWN_CLASS": 0,
		"WARRIOR":       1,
		"MAGE":          2,
		"RANGER":        3,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_server_client_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_server_client_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code   `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_UNKNOWN_CODE
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type OnPlayerConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *OnPlayerConnect) Reset() {
	*x = OnPlayerConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerConnect) ProtoMessage() {}

func (x *OnPlayerConnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerConnect.ProtoReflect.Descriptor instead.
func (*OnPlayerConnect) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{2}
}

func (x *OnPlayerConnect) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type OnPlayerDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *OnPlayerDisconnect) Reset() {
	*x = OnPlayerDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerDisconnect) ProtoMessage() {}

func (x *OnPlayerDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerDisconnect.ProtoReflect.Descriptor instead.
func (*OnPlayerDisconnect) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{3}
}

func (x *OnPlayerDisconnect) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Quit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *Quit) Reset() {
	*x = Quit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quit) ProtoMessage() {}

func (x *Quit) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quit.ProtoReflect.Descriptor instead.
func (*Quit) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{4}
}

func (x *Quit) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerList) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction float64 `protobuf:"fixed64,1,opt,name=direction,proto3" json:"direction,omitempty"`
	IsMoving  bool    `protobuf:"varint,2,opt,name=isMoving,proto3" json:"isMoving,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{6}
}

func (x *ClientInfo) GetDirection() float64 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *ClientInfo) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Class  Class   `protobuf:"varint,10,opt,name=class,proto3,enum=Class" json:"class,omitempty"`
	Hp     int64   `protobuf:"varint,11,opt,name=hp,proto3" json:"hp,omitempty"`
	Radius float64 `protobuf:"fixed64,12,opt,name=radius,proto3" json:"radius,omitempty"`
	Speed  float64 `protobuf:"fixed64,13,opt,name=speed,proto3" json:"speed,omitempty"`
	X      float64 `protobuf:"fixed64,20,opt,name=x,proto3" json:"x,omitempty"`
	Y      float64 `protobuf:"fixed64,21,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{7}
}

func (x *Player) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNKNOWN_CLASS
}

func (x *Player) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Player) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Player) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Player) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SpawnPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *SpawnPlayer) Reset() {
	*x = SpawnPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnPlayer) ProtoMessage() {}

func (x *SpawnPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnPlayer.ProtoReflect.Descriptor instead.
func (*SpawnPlayer) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{8}
}

func (x *SpawnPlayer) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type SetPlayerClass struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Class Class  `protobuf:"varint,2,opt,name=class,proto3,enum=Class" json:"class,omitempty"`
}

func (x *SetPlayerClass) Reset() {
	*x = SetPlayerClass{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerClass) ProtoMessage() {}

func (x *SetPlayerClass) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerClass.ProtoReflect.Descriptor instead.
func (*SetPlayerClass) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{9}
}

func (x *SetPlayerClass) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerClass) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNKNOWN_CLASS
}

type SetPlayerHP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hp int64  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
}

func (x *SetPlayerHP) Reset() {
	*x = SetPlayerHP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerHP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerHP) ProtoMessage() {}

func (x *SetPlayerHP) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerHP.ProtoReflect.Descriptor instead.
func (*SetPlayerHP) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{10}
}

func (x *SetPlayerHP) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerHP) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type SetPlayerRadius struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Radius float64 `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
}

func (x *SetPlayerRadius) Reset() {
	*x = SetPlayerRadius{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerRadius) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerRadius) ProtoMessage() {}

func (x *SetPlayerRadius) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerRadius.ProtoReflect.Descriptor instead.
func (*SetPlayerRadius) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{11}
}

func (x *SetPlayerRadius) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerRadius) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type SetPlayerSpeed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Speed float64 `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *SetPlayerSpeed) Reset() {
	*x = SetPlayerSpeed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerSpeed) ProtoMessage() {}

func (x *SetPlayerSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerSpeed.ProtoReflect.Descriptor instead.
func (*SetPlayerSpeed) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{12}
}

func (x *SetPlayerSpeed) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerSpeed) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type SetPlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X  float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y  float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *SetPlayerPosition) Reset() {
	*x = SetPlayerPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerPosition) ProtoMessage() {}

func (x *SetPlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerPosition.ProtoReflect.Descriptor instead.
func (*SetPlayerPosition) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{13}
}

func (x *SetPlayerPosition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerPosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SetPlayerPosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_server_client_proto protoreflect.FileDescriptor

var file_server_client_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2d, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x24,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x0f, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2f, 0x0a, 0x0a,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x46, 0x0a,
	0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x4d,
	0x6f, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d,
	0x6f, 0x76, 0x69, 0x6e, 0x67, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1c, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x06, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x68, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x14, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x0a, 0x4a, 0x04,
	0x08, 0x0e, 0x10, 0x14, 0x22, 0x2e, 0x0a, 0x0b, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x48, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x68, 0x70, 0x22, 0x39, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x22, 0x36,
	0x0a, 0x0e, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x70, 0x65, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x22, 0x3f, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x2a, 0x93, 0x02, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4f, 0x44, 0x45,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x41, 0x54, 0x43, 0x48, 0x10, 0x01, 0x12, 0x15, 0x0a,
	0x11, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45,
	0x43, 0x54, 0x10, 0x0a, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x0b, 0x12, 0x0f,
	0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0c, 0x12,
	0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0x14,
	0x12, 0x08, 0x0a, 0x04, 0x51, 0x55, 0x49, 0x54, 0x10, 0x15, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x50,
	0x41, 0x57, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x32, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53,
	0x10, 0x33, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x48, 0x50, 0x10, 0x34, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x52, 0x41, 0x44, 0x49, 0x55, 0x53, 0x10, 0x35, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x50, 0x45, 0x45, 0x44,
	0x10, 0x36, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x37, 0x22, 0x04, 0x08, 0x02, 0x10,
	0x09, 0x22, 0x04, 0x08, 0x0d, 0x10, 0x13, 0x22, 0x04, 0x08, 0x16, 0x10, 0x31, 0x2a, 0x3d, 0x0a,
	0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52,
	0x52, 0x49, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04,
	0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_client_proto_rawDescOnce sync.Once
	file_server_client_proto_rawDescData = file_server_client_proto_rawDesc
)

func file_server_client_proto_rawDescGZIP() []byte {
	file_server_client_proto_rawDescOnce.Do(func() {
		file_server_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_client_proto_rawDescData)
	})
	return file_server_client_proto_rawDescData
}

var file_server_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_client_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_server_client_proto_goTypes = []interface{}{
	(Code)(0),                  // 0: Code
	(Class)(0),                 // 1: Class
	(*Message)(nil),            // 2: Message
	(*Batch)(nil),              // 3: Batch
	(*OnPlayerConnect)(nil),    // 4: OnPlayerConnect
	(*OnPlayerDisconnect)(nil), // 5: OnPlayerDisconnect
	(*Quit)(nil),               // 6: Quit
	(*PlayerList)(nil),         // 7: PlayerList
	(*ClientInfo)(nil),         // 8: ClientInfo
	(*Player)(nil),             // 9: Player
	(*SpawnPlayer)(nil),        // 10: SpawnPlayer
	(*SetPlayerClass)(nil),     // 11: SetPlayerClass
	(*SetPlayerHP)(nil),        // 12: SetPlayerHP
	(*SetPlayerRadius)(nil),    // 13: SetPlayerRadius
	(*SetPlayerSpeed)(nil),     // 14: SetPlayerSpeed
	(*SetPlayerPosition)(nil),  // 15: SetPlayerPosition
}
var file_server_client_proto_depIdxs = []int32{
	0, // 0: Message.code:type_name -> Code
	2, // 1: Batch.messages:type_name -> Message
	9, // 2: PlayerList.players:type_name -> Player
	1, // 3: Player.class:type_name -> Class
	9, // 4: SpawnPlayer.player:type_name -> Player
	1, // 5: SetPlayerClass.class:type_name -> Class
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_server_client_proto_init() }
func file_server_client_proto_init() {
	if File_server_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerClass); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerHP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerRadius); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerSpeed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_client_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_client_proto_goTypes,
		DependencyIndexes: file_server_client_proto_depIdxs,
		EnumInfos:         file_server_client_proto_enumTypes,
		MessageInfos:      file_server_client_proto_msgTypes,
	}.Build()
	File_server_client_proto = out.File
	file_server_client_proto_rawDesc = nil
	file_server_client_proto_goTypes = nil
	file_server_client_proto_depIdxs = nil
}
