// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: server_client.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_UNKNOWN_CODE            Code = 0
	Code_BATCH                   Code = 1
	Code_ON_PLAYER_CONNECT       Code = 10
	Code_ON_PLAYER_DISCONNECT    Code = 11
	Code_ON_PLAYER_WASTED        Code = 12
	Code_ON_PLAYER_ATTACKED      Code = 13
	Code_PLAYER_LIST             Code = 30
	Code_WORLD_INFO              Code = 31
	Code_CLIENT_INFO             Code = 50
	Code_QUIT                    Code = 51
	Code_BE_REBORN               Code = 52
	Code_SPAWN_PLAYER            Code = 70
	Code_SET_PLAYER_STATS        Code = 71
	Code_SET_PLAYER_HP           Code = 72
	Code_SET_PLAYER_POSITION     Code = 73
	Code_SET_PLAYER_WEAPON       Code = 74
	Code_CREATE_PROJECTILE       Code = 90
	Code_SET_PROJECTILE_POSITION Code = 91
	Code_DELETE_PROJECTILE       Code = 92
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "UNKNOWN_CODE",
		1:  "BATCH",
		10: "ON_PLAYER_CONNECT",
		11: "ON_PLAYER_DISCONNECT",
		12: "ON_PLAYER_WASTED",
		13: "ON_PLAYER_ATTACKED",
		30: "PLAYER_LIST",
		31: "WORLD_INFO",
		50: "CLIENT_INFO",
		51: "QUIT",
		52: "BE_REBORN",
		70: "SPAWN_PLAYER",
		71: "SET_PLAYER_STATS",
		72: "SET_PLAYER_HP",
		73: "SET_PLAYER_POSITION",
		74: "SET_PLAYER_WEAPON",
		90: "CREATE_PROJECTILE",
		91: "SET_PROJECTILE_POSITION",
		92: "DELETE_PROJECTILE",
	}
	Code_value = map[string]int32{
		"UNKNOWN_CODE":            0,
		"BATCH":                   1,
		"ON_PLAYER_CONNECT":       10,
		"ON_PLAYER_DISCONNECT":    11,
		"ON_PLAYER_WASTED":        12,
		"ON_PLAYER_ATTACKED":      13,
		"PLAYER_LIST":             30,
		"WORLD_INFO":              31,
		"CLIENT_INFO":             50,
		"QUIT":                    51,
		"BE_REBORN":               52,
		"SPAWN_PLAYER":            70,
		"SET_PLAYER_STATS":        71,
		"SET_PLAYER_HP":           72,
		"SET_PLAYER_POSITION":     73,
		"SET_PLAYER_WEAPON":       74,
		"CREATE_PROJECTILE":       90,
		"SET_PROJECTILE_POSITION": 91,
		"DELETE_PROJECTILE":       92,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_server_client_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_server_client_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{0}
}

type Class int32

const (
	Class_UNKNOWN_CLASS Class = 0
	Class_WARRIOR       Class = 1
	Class_MAGE          Class = 2
	Class_RANGER        Class = 3
)

// Enum value maps for Class.
var (
	Class_name = map[int32]string{
		0: "UNKNOWN_CLASS",
		1: "WARRIOR",
		2: "MAGE",
		3: "RANGER",
	}
	Class_value = map[string]int32{
		"UNKNOWN_CLASS": 0,
		"WARRIOR":       1,
		"MAGE":          2,
		"RANGER":        3,
	}
)

func (x Class) Enum() *Class {
	p := new(Class)
	*p = x
	return p
}

func (x Class) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Class) Descriptor() protoreflect.EnumDescriptor {
	return file_server_client_proto_enumTypes[1].Descriptor()
}

func (Class) Type() protoreflect.EnumType {
	return &file_server_client_proto_enumTypes[1]
}

func (x Class) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Class.Descriptor instead.
func (Class) EnumDescriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    Code   `protobuf:"varint,1,opt,name=code,proto3,enum=Code" json:"code,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_UNKNOWN_CODE
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rgba uint32 `protobuf:"varint,1,opt,name=rgba,proto3" json:"rgba,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{3}
}

func (x *Color) GetRgba() uint32 {
	if x != nil {
		return x.Rgba
	}
	return 0
}

type OnPlayerConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *OnPlayerConnect) Reset() {
	*x = OnPlayerConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerConnect) ProtoMessage() {}

func (x *OnPlayerConnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerConnect.ProtoReflect.Descriptor instead.
func (*OnPlayerConnect) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{4}
}

func (x *OnPlayerConnect) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type OnPlayerDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *OnPlayerDisconnect) Reset() {
	*x = OnPlayerDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerDisconnect) ProtoMessage() {}

func (x *OnPlayerDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerDisconnect.ProtoReflect.Descriptor instead.
func (*OnPlayerDisconnect) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{5}
}

func (x *OnPlayerDisconnect) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type OnPlayerWasted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Killer uint64 `protobuf:"varint,2,opt,name=killer,proto3" json:"killer,omitempty"`
}

func (x *OnPlayerWasted) Reset() {
	*x = OnPlayerWasted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerWasted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerWasted) ProtoMessage() {}

func (x *OnPlayerWasted) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerWasted.ProtoReflect.Descriptor instead.
func (*OnPlayerWasted) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{6}
}

func (x *OnPlayerWasted) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnPlayerWasted) GetKiller() uint64 {
	if x != nil {
		return x.Killer
	}
	return 0
}

type Quit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Quit) Reset() {
	*x = Quit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quit) ProtoMessage() {}

func (x *Quit) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quit.ProtoReflect.Descriptor instead.
func (*Quit) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{7}
}

type BeReborn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeReborn) Reset() {
	*x = BeReborn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeReborn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeReborn) ProtoMessage() {}

func (x *BeReborn) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeReborn.ProtoReflect.Descriptor instead.
func (*BeReborn) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{8}
}

type PlayerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *PlayerList) Reset() {
	*x = PlayerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerList) ProtoMessage() {}

func (x *PlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerList.ProtoReflect.Descriptor instead.
func (*PlayerList) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerList) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type WorldInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Northwest *Point `protobuf:"bytes,1,opt,name=northwest,proto3" json:"northwest,omitempty"`
	Southeast *Point `protobuf:"bytes,2,opt,name=southeast,proto3" json:"southeast,omitempty"`
}

func (x *WorldInfo) Reset() {
	*x = WorldInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldInfo) ProtoMessage() {}

func (x *WorldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldInfo.ProtoReflect.Descriptor instead.
func (*WorldInfo) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{10}
}

func (x *WorldInfo) GetNorthwest() *Point {
	if x != nil {
		return x.Northwest
	}
	return nil
}

func (x *WorldInfo) GetSoutheast() *Point {
	if x != nil {
		return x.Southeast
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction    float64 `protobuf:"fixed64,1,opt,name=direction,proto3" json:"direction,omitempty"`
	IsMoving     bool    `protobuf:"varint,2,opt,name=isMoving,proto3" json:"isMoving,omitempty"`
	Attack       bool    `protobuf:"varint,3,opt,name=attack,proto3" json:"attack,omitempty"`
	DirectionAim float64 `protobuf:"fixed64,4,opt,name=direction_aim,json=directionAim,proto3" json:"direction_aim,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{11}
}

func (x *ClientInfo) GetDirection() float64 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *ClientInfo) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

func (x *ClientInfo) GetAttack() bool {
	if x != nil {
		return x.Attack
	}
	return false
}

func (x *ClientInfo) GetDirectionAim() float64 {
	if x != nil {
		return x.DirectionAim
	}
	return 0
}

type PlayerStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Class  Class   `protobuf:"varint,1,opt,name=class,proto3,enum=Class" json:"class,omitempty"`
	Radius float64 `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
	Speed  float64 `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	MaxHP  int32   `protobuf:"varint,4,opt,name=maxHP,proto3" json:"maxHP,omitempty"`
	Resist *Resist `protobuf:"bytes,5,opt,name=resist,proto3" json:"resist,omitempty"`
}

func (x *PlayerStats) Reset() {
	*x = PlayerStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStats) ProtoMessage() {}

func (x *PlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStats.ProtoReflect.Descriptor instead.
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerStats) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_UNKNOWN_CLASS
}

func (x *PlayerStats) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *PlayerStats) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerStats) GetMaxHP() int32 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *PlayerStats) GetResist() *Resist {
	if x != nil {
		return x.Resist
	}
	return nil
}

type Resist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Physical float64 `protobuf:"fixed64,1,opt,name=physical,proto3" json:"physical,omitempty"`
	Magical  float64 `protobuf:"fixed64,2,opt,name=magical,proto3" json:"magical,omitempty"`
}

func (x *Resist) Reset() {
	*x = Resist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resist) ProtoMessage() {}

func (x *Resist) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resist.ProtoReflect.Descriptor instead.
func (*Resist) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{13}
}

func (x *Resist) GetPhysical() float64 {
	if x != nil {
		return x.Physical
	}
	return 0
}

func (x *Resist) GetMagical() float64 {
	if x != nil {
		return x.Magical
	}
	return 0
}

type Weapon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Damage   *Damage `protobuf:"bytes,10,opt,name=damage,proto3" json:"damage,omitempty"`
	CoolDown float64 `protobuf:"fixed64,12,opt,name=cool_down,json=coolDown,proto3" json:"cool_down,omitempty"`
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{14}
}

func (x *Weapon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Weapon) GetDamage() *Damage {
	if x != nil {
		return x.Damage
	}
	return nil
}

func (x *Weapon) GetCoolDown() float64 {
	if x != nil {
		return x.CoolDown
	}
	return 0
}

type Damage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Physical int32 `protobuf:"varint,1,opt,name=physical,proto3" json:"physical,omitempty"`
	Magical  int32 `protobuf:"varint,2,opt,name=magical,proto3" json:"magical,omitempty"`
}

func (x *Damage) Reset() {
	*x = Damage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Damage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Damage) ProtoMessage() {}

func (x *Damage) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Damage.ProtoReflect.Descriptor instead.
func (*Damage) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{15}
}

func (x *Damage) GetPhysical() int32 {
	if x != nil {
		return x.Physical
	}
	return 0
}

func (x *Damage) GetMagical() int32 {
	if x != nil {
		return x.Magical
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats  *PlayerStats `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	Weapon *Weapon      `protobuf:"bytes,11,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Hp     int32        `protobuf:"varint,20,opt,name=hp,proto3" json:"hp,omitempty"`
	X      float64      `protobuf:"fixed64,21,opt,name=x,proto3" json:"x,omitempty"`
	Y      float64      `protobuf:"fixed64,22,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{16}
}

func (x *Player) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetStats() *PlayerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Player) GetWeapon() *Weapon {
	if x != nil {
		return x.Weapon
	}
	return nil
}

func (x *Player) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Player) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SpawnPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *SpawnPlayer) Reset() {
	*x = SpawnPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpawnPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnPlayer) ProtoMessage() {}

func (x *SpawnPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnPlayer.ProtoReflect.Descriptor instead.
func (*SpawnPlayer) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{17}
}

func (x *SpawnPlayer) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type SetPlayerStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats *PlayerStats `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *SetPlayerStats) Reset() {
	*x = SetPlayerStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerStats) ProtoMessage() {}

func (x *SetPlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerStats.ProtoReflect.Descriptor instead.
func (*SetPlayerStats) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{18}
}

func (x *SetPlayerStats) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerStats) GetStats() *PlayerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type SetPlayerHP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hp int32  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
}

func (x *SetPlayerHP) Reset() {
	*x = SetPlayerHP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerHP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerHP) ProtoMessage() {}

func (x *SetPlayerHP) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerHP.ProtoReflect.Descriptor instead.
func (*SetPlayerHP) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{19}
}

func (x *SetPlayerHP) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerHP) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

type SetPlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X  float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y  float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *SetPlayerPosition) Reset() {
	*x = SetPlayerPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerPosition) ProtoMessage() {}

func (x *SetPlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerPosition.ProtoReflect.Descriptor instead.
func (*SetPlayerPosition) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{20}
}

func (x *SetPlayerPosition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerPosition) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SetPlayerPosition) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SetPlayerWeapon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Weapon *Weapon `protobuf:"bytes,2,opt,name=weapon,proto3" json:"weapon,omitempty"`
}

func (x *SetPlayerWeapon) Reset() {
	*x = SetPlayerWeapon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerWeapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerWeapon) ProtoMessage() {}

func (x *SetPlayerWeapon) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerWeapon.ProtoReflect.Descriptor instead.
func (*SetPlayerWeapon) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{21}
}

func (x *SetPlayerWeapon) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetPlayerWeapon) GetWeapon() *Weapon {
	if x != nil {
		return x.Weapon
	}
	return nil
}

type OnPlayerAttacked struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DirectionAim float64 `protobuf:"fixed64,2,opt,name=directionAim,proto3" json:"directionAim,omitempty"`
}

func (x *OnPlayerAttacked) Reset() {
	*x = OnPlayerAttacked{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnPlayerAttacked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnPlayerAttacked) ProtoMessage() {}

func (x *OnPlayerAttacked) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnPlayerAttacked.ProtoReflect.Descriptor instead.
func (*OnPlayerAttacked) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{22}
}

func (x *OnPlayerAttacked) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OnPlayerAttacked) GetDirectionAim() float64 {
	if x != nil {
		return x.DirectionAim
	}
	return 0
}

type Projectile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Color     *Color  `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Position  *Point  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Radius    float64 `protobuf:"fixed64,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Speed     float64 `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Direction float64 `protobuf:"fixed64,6,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *Projectile) Reset() {
	*x = Projectile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Projectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projectile) ProtoMessage() {}

func (x *Projectile) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projectile.ProtoReflect.Descriptor instead.
func (*Projectile) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{23}
}

func (x *Projectile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Projectile) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Projectile) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Projectile) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Projectile) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Projectile) GetDirection() float64 {
	if x != nil {
		return x.Direction
	}
	return 0
}

type CreateProjectile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projectile *Projectile `protobuf:"bytes,1,opt,name=projectile,proto3" json:"projectile,omitempty"`
}

func (x *CreateProjectile) Reset() {
	*x = CreateProjectile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateProjectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectile) ProtoMessage() {}

func (x *CreateProjectile) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectile.ProtoReflect.Descriptor instead.
func (*CreateProjectile) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{24}
}

func (x *CreateProjectile) GetProjectile() *Projectile {
	if x != nil {
		return x.Projectile
	}
	return nil
}

type SetProjectilePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position *Point `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *SetProjectilePosition) Reset() {
	*x = SetProjectilePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProjectilePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProjectilePosition) ProtoMessage() {}

func (x *SetProjectilePosition) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProjectilePosition.ProtoReflect.Descriptor instead.
func (*SetProjectilePosition) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{25}
}

func (x *SetProjectilePosition) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetProjectilePosition) GetPosition() *Point {
	if x != nil {
		return x.Position
	}
	return nil
}

type DeleteProjectile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteProjectile) Reset() {
	*x = DeleteProjectile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_client_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteProjectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectile) ProtoMessage() {}

func (x *DeleteProjectile) ProtoReflect() protoreflect.Message {
	mi := &file_server_client_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectile.ProtoReflect.Descriptor instead.
func (*DeleteProjectile) Descriptor() ([]byte, []int) {
	return file_server_client_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteProjectile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_server_client_proto protoreflect.FileDescriptor

var file_server_client_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x05,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x2d, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x24,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x08, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x1b, 0x0a, 0x05, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x67, 0x62, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x72, 0x67, 0x62, 0x61, 0x22, 0x2e, 0x0a, 0x0f, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0e, 0x4f, 0x6e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x61, 0x73, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6b,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6b, 0x69, 0x6c,
	0x6c, 0x65, 0x72, 0x22, 0x06, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x42,
	0x65, 0x52, 0x65, 0x62, 0x6f, 0x72, 0x6e, 0x22, 0x2f, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x57, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x24, 0x0a, 0x09, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x77, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x09, 0x6e, 0x6f, 0x72, 0x74, 0x68, 0x77, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x09, 0x73,
	0x6f, 0x75, 0x74, 0x68, 0x65, 0x61, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x74, 0x68, 0x65, 0x61, 0x73,
	0x74, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x4d, 0x6f, 0x76, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x74,
	0x74, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x61, 0x69, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x69, 0x6d, 0x22, 0x90, 0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x50, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x48, 0x50, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x69,
	0x73, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x69, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x06, 0x52, 0x65,
	0x73, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x07, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x66, 0x0a, 0x06, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x44, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6f,
	0x6c, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x63, 0x6f,
	0x6f, 0x6c, 0x44, 0x6f, 0x77, 0x6e, 0x4a, 0x04, 0x08, 0x02, 0x10, 0x0a, 0x4a, 0x04, 0x08, 0x0b,
	0x10, 0x0c, 0x22, 0x3e, 0x0a, 0x06, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x67, 0x69,
	0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x67, 0x69, 0x63,
	0x61, 0x6c, 0x22, 0x95, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x1f, 0x0a, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x77, 0x65, 0x61, 0x70,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x14, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x68, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x15, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x16, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x4a, 0x04,
	0x08, 0x02, 0x10, 0x0a, 0x4a, 0x04, 0x08, 0x0c, 0x10, 0x14, 0x22, 0x2e, 0x0a, 0x0b, 0x53, 0x70,
	0x61, 0x77, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x22, 0x2d, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x50, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x22,
	0x3f, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79,
	0x22, 0x42, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x52, 0x06, 0x77, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x10, 0x4f, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x69, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x69, 0x6d, 0x22, 0xaa, 0x01, 0x0a,
	0x0a, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72,
	0x61, 0x64, 0x69, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x2b, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x22, 0x4b, 0x0a, 0x15, 0x53, 0x65,
	0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x2a, 0xa1, 0x03, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x41, 0x54, 0x43, 0x48, 0x10,
	0x01, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x0a, 0x12, 0x18, 0x0a, 0x14, 0x4f, 0x4e, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x10, 0x0b, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f,
	0x57, 0x41, 0x53, 0x54, 0x45, 0x44, 0x10, 0x0c, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x4e, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x0d,
	0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10,
	0x1e, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x10,
	0x1f, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f,
	0x10, 0x32, 0x12, 0x08, 0x0a, 0x04, 0x51, 0x55, 0x49, 0x54, 0x10, 0x33, 0x12, 0x0d, 0x0a, 0x09,
	0x42, 0x45, 0x5f, 0x52, 0x45, 0x42, 0x4f, 0x52, 0x4e, 0x10, 0x34, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x50, 0x41, 0x57, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x46, 0x12, 0x14, 0x0a,
	0x10, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x53, 0x10, 0x47, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45,
	0x52, 0x5f, 0x48, 0x50, 0x10, 0x48, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c,
	0x41, 0x59, 0x45, 0x52, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x49, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x57, 0x45,
	0x41, 0x50, 0x4f, 0x4e, 0x10, 0x4a, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45, 0x10, 0x5a, 0x12, 0x1b, 0x0a,
	0x17, 0x53, 0x45, 0x54, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45, 0x5f,
	0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x5b, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x49, 0x4c, 0x45, 0x10,
	0x5c, 0x22, 0x04, 0x08, 0x02, 0x10, 0x09, 0x22, 0x04, 0x08, 0x0e, 0x10, 0x1d, 0x22, 0x04, 0x08,
	0x20, 0x10, 0x31, 0x22, 0x04, 0x08, 0x35, 0x10, 0x45, 0x22, 0x04, 0x08, 0x4b, 0x10, 0x59, 0x2a,
	0x3d, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57,
	0x41, 0x52, 0x52, 0x49, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x47, 0x45,
	0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x10, 0x03, 0x42, 0x06,
	0x5a, 0x04, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_client_proto_rawDescOnce sync.Once
	file_server_client_proto_rawDescData = file_server_client_proto_rawDesc
)

func file_server_client_proto_rawDescGZIP() []byte {
	file_server_client_proto_rawDescOnce.Do(func() {
		file_server_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_client_proto_rawDescData)
	})
	return file_server_client_proto_rawDescData
}

var file_server_client_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_client_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_server_client_proto_goTypes = []interface{}{
	(Code)(0),                     // 0: Code
	(Class)(0),                    // 1: Class
	(*Message)(nil),               // 2: Message
	(*Batch)(nil),                 // 3: Batch
	(*Point)(nil),                 // 4: Point
	(*Color)(nil),                 // 5: Color
	(*OnPlayerConnect)(nil),       // 6: OnPlayerConnect
	(*OnPlayerDisconnect)(nil),    // 7: OnPlayerDisconnect
	(*OnPlayerWasted)(nil),        // 8: OnPlayerWasted
	(*Quit)(nil),                  // 9: Quit
	(*BeReborn)(nil),              // 10: BeReborn
	(*PlayerList)(nil),            // 11: PlayerList
	(*WorldInfo)(nil),             // 12: WorldInfo
	(*ClientInfo)(nil),            // 13: ClientInfo
	(*PlayerStats)(nil),           // 14: PlayerStats
	(*Resist)(nil),                // 15: Resist
	(*Weapon)(nil),                // 16: Weapon
	(*Damage)(nil),                // 17: Damage
	(*Player)(nil),                // 18: Player
	(*SpawnPlayer)(nil),           // 19: SpawnPlayer
	(*SetPlayerStats)(nil),        // 20: SetPlayerStats
	(*SetPlayerHP)(nil),           // 21: SetPlayerHP
	(*SetPlayerPosition)(nil),     // 22: SetPlayerPosition
	(*SetPlayerWeapon)(nil),       // 23: SetPlayerWeapon
	(*OnPlayerAttacked)(nil),      // 24: OnPlayerAttacked
	(*Projectile)(nil),            // 25: Projectile
	(*CreateProjectile)(nil),      // 26: CreateProjectile
	(*SetProjectilePosition)(nil), // 27: SetProjectilePosition
	(*DeleteProjectile)(nil),      // 28: DeleteProjectile
}
var file_server_client_proto_depIdxs = []int32{
	0,  // 0: Message.code:type_name -> Code
	2,  // 1: Batch.messages:type_name -> Message
	18, // 2: PlayerList.players:type_name -> Player
	4,  // 3: WorldInfo.northwest:type_name -> Point
	4,  // 4: WorldInfo.southeast:type_name -> Point
	1,  // 5: PlayerStats.class:type_name -> Class
	15, // 6: PlayerStats.resist:type_name -> Resist
	17, // 7: Weapon.damage:type_name -> Damage
	14, // 8: Player.stats:type_name -> PlayerStats
	16, // 9: Player.weapon:type_name -> Weapon
	18, // 10: SpawnPlayer.player:type_name -> Player
	14, // 11: SetPlayerStats.stats:type_name -> PlayerStats
	16, // 12: SetPlayerWeapon.weapon:type_name -> Weapon
	5,  // 13: Projectile.color:type_name -> Color
	4,  // 14: Projectile.position:type_name -> Point
	25, // 15: CreateProjectile.projectile:type_name -> Projectile
	4,  // 16: SetProjectilePosition.position:type_name -> Point
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_server_client_proto_init() }
func file_server_client_proto_init() {
	if File_server_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerWasted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeReborn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Weapon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Damage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpawnPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerHP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerWeapon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnPlayerAttacked); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Projectile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateProjectile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProjectilePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_client_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteProjectile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_client_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_client_proto_goTypes,
		DependencyIndexes: file_server_client_proto_depIdxs,
		EnumInfos:         file_server_client_proto_enumTypes,
		MessageInfos:      file_server_client_proto_msgTypes,
	}.Build()
	File_server_client_proto = out.File
	file_server_client_proto_rawDesc = nil
	file_server_client_proto_goTypes = nil
	file_server_client_proto_depIdxs = nil
}
